Repository uniyunnnn/Instagram, pull requests merged in 2023-06, with the labels that each got.

#11 <docs> jihye update .gitignore
  src/main/resources/application.yml
Labels: 📝Docs, 🛢인프라

#17 <feat> 로그인 세션정보 확인해보기
  src/main/java/com/cos/photogramstart/config/auth/PrincipalDetails.java
  src/main/java/com/cos/photogramstart/web/UserController.java
  src/main/resources/application.yml
Labels: 🎉FEAT

#18 <feat> 회원정보수정 시큐리티 태그라이브러리
  src/main/java/com/cos/photogramstart/web/UserController.java
  src/main/webapp/WEB-INF/views/layout/header.jsp
  src/main/webapp/WEB-INF/views/user/update.jsp
Labels: 🎉FEAT

#19 <feat> 회원정보수정 완료(영속성 추가)
  src/main/java/com/cos/photogramstart/service/UserService.java
  src/main/java/com/cos/photogramstart/web/dto/user/UserUpdateDto.java
  src/main/resources/static/js/update.js
  src/main/webapp/WEB-INF/views/user/update.jsp
Labels: 🎉FEAT, 백엔드

#20 <feat> 모델 만들기
  src/main/java/com/cos/photogramstart/domain/subscribe/Subscribe.java
  src/main/java/com/cos/photogramstart/domain/subscribe/SubscribeRepository.java
Labels: 🛢인프라

#21 <feat> <bug> 구독, 구독취소 API 만들기
  src/main/java/com/cos/photogramstart/domain/subscribe/SubscribeRepository.java
  src/main/java/com/cos/photogramstart/handler/ControllerExceptionHandler.java
  src/main/java/com/cos/photogramstart/service/SubscribeService.java
  src/main/java/com/cos/photogramstart/web/api/SubscribeApiController.java
Labels: 🎉FEAT, 👾버그

#22 <Bugfix> 구독,구독취소 API 만들기 버그 수정
  src/main/java/com/cos/photogramstart/domain/subscribe/SubscribeRepository.java
  src/main/java/com/cos/photogramstart/web/api/SubscribeApiController.java
Labels: 👾버그

#23 <Bugfix> 구독하기,구독취소하기 API생성 버그수정
  src/main/java/com/cos/photogramstart/domain/subscribe/SubscribeRepository.java
  src/main/java/com/cos/photogramstart/service/SubscribeService.java
Labels: 👾버그

#24 <bug> 구독하기 버그 수정
  src/main/java/com/cos/photogramstart/domain/subscribe/SubscribeRepository.java
  src/main/java/com/cos/photogramstart/web/api/UserApiController.java
Labels: 👾버그

#25 <bug>구독하기 버그
  src/main/java/com/cos/photogramstart/config/auth/PrincipalDetails.java
  src/main/java/com/cos/photogramstart/domain/subscribe/SubscribeRepository.java
Labels: 👾버그

#27 <Bugfix> 구독하기 - 글로벌 예외 처리하기, API주소 시큐리티 설정하기 버그수정
  src/main/java/com/cos/photogramstart/handler/ControllerExceptionHandler.java
Labels: 👾버그

#29 image 양방향 매핑 이해하기
  src/main/java/com/cos/photogramstart/domain/user/Users.java
  src/main/java/com/cos/photogramstart/handler/ControllerExceptionHandler.java
  src/main/java/com/cos/photogramstart/handler/ex/CustomException.java
  src/main/java/com/cos/photogramstart/service/ImageService.java
  src/main/java/com/cos/photogramstart/service/UserService.java
  src/main/java/com/cos/photogramstart/web/ImageController.java
  src/main/java/com/cos/photogramstart/web/UserController.java
  src/main/java/com/cos/photogramstart/web/dto/image/ImageUploadDto.java
  src/main/webapp/WEB-INF/views/image/upload.jsp
Labels: 🛢인프라, 🎉FEAT, 백엔드

#30 <Bug>프로필페이지 - DTO로 프로필페이지 완성하기
  src/main/java/com/cos/photogramstart/domain/user/Users.java
  src/main/java/com/cos/photogramstart/service/UserService.java
  src/main/java/com/cos/photogramstart/web/UserController.java
  src/main/java/com/cos/photogramstart/web/api/UserApiController.java
  src/main/java/com/cos/photogramstart/web/dto/user/UserProfileDto.java
  src/main/webapp/WEB-INF/views/user/profile.jsp
Labels: 🎉FEAT, 백엔드, 👾버그
