Repository uniyunnnn/Instagram, pull requests merged in 2023-07, with the labels that each got.

#33 <Bug> DTO매핑하기(QLRM 라이브러리로 DTO 매핑하기)
  src/main/java/com/cos/photogramstart/domain/subscribe/SubscribeRepository.java
  src/main/java/com/cos/photogramstart/service/SubscribeService.java
  src/main/java/com/cos/photogramstart/web/api/UserApiController.java
  src/main/java/com/cos/photogramstart/web/dto/subscribe/SubscribeDto.java
Labels: 👾버그

#34 <feat> 구독모달 정보 렌더링 완료
  src/main/resources/static/js/profile.js
  src/main/webapp/WEB-INF/views/user/profile.jsp
Labels: 🖼프론트엔드

#35 <feat> 포토리스트 API 만들기
  src/main/java/com/cos/photogramstart/domain/image/Image.java
  src/main/java/com/cos/photogramstart/domain/image/ImageRepository.java
  src/main/java/com/cos/photogramstart/service/ImageService.java
  src/main/java/com/cos/photogramstart/web/api/ImageApiController.java
Labels: 🎉FEAT, 백엔드

#37 <feat>좋아요 구현 - 좋아요 뷰 렌더링
  src/main/java/com/cos/photogramstart/domain/image/Image.java
  src/main/java/com/cos/photogramstart/service/ImageService.java
  src/main/resources/static/js/story.js
Labels: 🎉FEAT

#38 <feat>좋아요 구현 - 좋아요 카운트 뷰 렌더링
  src/main/java/com/cos/photogramstart/domain/image/Image.java
  src/main/java/com/cos/photogramstart/service/ImageService.java
  src/main/resources/static/js/story.js
  src/main/webapp/WEB-INF/views/user/profile.jsp
Labels: 🎉FEAT

#39 <fix> 오류 수정
  src/main/webapp/WEB-INF/views/user/profile.jsp
Labels: 👾버그

#40 <feat> 프로필 페이지 좋아요 카운트 구현
  src/main/java/com/cos/photogramstart/service/UserService.java
  src/main/webapp/WEB-INF/views/user/profile.jsp
Labels: 🎉FEAT, 백엔드

#41 <feat> 댓글 - 댓글쓰기 Ajax 함수 만들기
  src/main/java/com/cos/photogramstart/domain/comment/CommentRepository.java
  src/main/java/com/cos/photogramstart/domain/comment/Comments.java
  src/main/java/com/cos/photogramstart/service/CommentService.java
  src/main/java/com/cos/photogramstart/web/api/CommentApiController.java
  src/main/java/com/cos/photogramstart/web/dto/comment/CommentDto.java
  src/main/resources/static/js/story.js
Labels: 🎉FEAT

#42 <feat> 댓글 View 랜더링하기
  src/main/java/com/cos/photogramstart/domain/comment/Comments.java
  src/main/java/com/cos/photogramstart/domain/image/Image.java
  src/main/resources/static/js/story.js
Labels: 🎉FEAT

#44 <feat> 댓글 유효성 검사
  src/main/java/com/cos/photogramstart/web/api/CommentApiController.java
  src/main/java/com/cos/photogramstart/web/dto/comment/CommentDto.java
  src/main/resources/static/js/story.js
Labels: 🛠 Refactoring

#45 <feat> Google소셜 로그인
  pom.xml
  src/main/java/com/cos/photogramstart/config/SecurityConfig.java
  src/main/java/com/cos/photogramstart/config/auth/PrincipalDetails.java
  src/main/java/com/cos/photogramstart/config/oauth/GoogleInfo.java
  src/main/java/com/cos/photogramstart/config/oauth/OAuth2DetailsService.java
  src/main/java/com/cos/photogramstart/config/oauth/OAuth2UserInfo.java
  src/main/java/com/cos/photogramstart/domain/user/Users.java
  src/main/resources/application.yml
  src/main/resources/static/css/style.css
  src/main/resources/static/images/google.png
  src/main/resources/static/images/kakao.png
  src/main/resources/static/images/naver.png
  src/main/webapp/WEB-INF/views/auth/signin.jsp
Labels: 🎉FEAT
